### ISSUE TITLE
On-off-on switch

### ISSUE THREAD

**Issue by godbless876** [SwitchAndLever/theMIDInator#1]
Hey.. this project seems like the solution to an issue I have been fighting with.. I want to know tho.. the on-off-on switch for transpose is tied to ground right? And the increment values can also be changed to 1 note increments instead of 12 right?

**Comment by SwitchAndLever** [comment]
Apologies for replying months late. Yes, all buttons/switches are tied to ground. Increment values can be changed in any interval you wish by changing the code. Only reason it's 12 is because that is all the keys/notes (on a piano) in one octave.
